name: galih_apps
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  nima: ^1.0.5
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/img/anak-smp.jpg
    - lib/assets/anim/Newton.nima
    - lib/assets/anim/Newton0.png
    - lib/assets/anim/Newton1.png
    - lib/assets/anim/Newton2.png
    - lib/assets/anim/Newton3.png
    - lib/assets/anim/Newton4.png
    - lib/assets/anim/Newton5.png

  fonts:
    - family: Lato
      fonts:
        - asset: lib/assets/fonts/Lato-Regular.ttf
        - asset: lib/assets/fonts/Lato-Italic.ttf
          style: italic
        - asset: lib/assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Lato-BoldItalic.ttf
          weight: 700
          style: italic
